include: "rules/common.smk"


if lookup_config(dpath="load_fair_genome_indexer_pipeline", default=True):

    include: "rules/fair_genome_indexer_pipeline.smk"


if lookup_config(dpath="load_fair_bowtie2_mapping_pipeline", default=True):

    include: "rules/fair_bowtie2_mapping_pipeline.smk"


if lookup_config(dpath="load_fair_fastqc_multiqc_pipeline", default=True):

    include: "rules/fair_fastqc_multiqc_pipeline.smk"


include: "rules/bcftools.smk"
include: "rules/gatk_mutect2_calling_meta.smk"
include: "rules/gatk.smk"
include: "rules/multiqc.smk"
include: "rules/snpeff.smk"
include: "rules/snpsift.smk"


rule gatk_mutect2_targets:
    input:
        unpack(get_gatk_mutect2_targets),
    output:
        touch("tmp/targets/gatk_mutect2_targets.txt"),
    log:
        "logs/gatk_mutect2_targets.log",
    benchmark:
        "benchmark/gatk_mutect2_targets.tsv"
