---
$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

genomes:
  type: string
  description: Path to the CSV file defining genome properties

load_fair_genome_indexer:
  type: boolean
  description: Load (or not) the fair_genome_indexer pipeline. Internal use only.

load_fair_fastqc_multiqc:
  type: boolean
  description: Load (or not) the fair_fastqc_multiqc pipeline. Internal use only.

load_fair_bowtie2_mapping:
  type: boolean
  description: Load (or not the fair_bowtie2_mapping pipeline. Internal use only.

samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths

# This pipeline supports the exact parameters provided in these documentation
# fair_genome_indexer: see https://github.com/tdayris/fair_genome_indexer/blob/main/workflow/schemas/config.schema.yaml
# fair_fastqc_multiqc: see https://github.com/tdayris/fair_fastqc_multiqc/blob/main/workflow/schemas/config.schema.yaml
# fair_bowtie2_mapping: see https://github.com/tdayris/fair_bowtie2_mapping/blob/main/workflow/schemas/config.schema.yaml
# Note: Do not change the pipeline name in the parameteres.
# Leave fair_fastqc_multiqc or fair_genome_indexer
# as they are written in their original configuration file.
# This is used to disambiguate many parameters.

params:
  type: object
  description: Optional parameters for all (sub) pipelines

  fair_gatk_mutect2:
    type: object
    description: Optional parameters for this pipeline

    bcftools:
      type: object
      description: Optional parameters for all BCFtools subcommands

      view:
        type: string
        description: Optional parameters for filtering and compressions
        default: ""

      stats:
        type: string
        description: Optional parameters for variants statistics
        default: ""

      gatk:
        type: object
        description: Optional parameters for all GATK subcommands

        mutect2:
          type: string
          description: Optional parameters for Mutect2 call
          default: ""

        getpileupsummries:
          type: string
          description: Optional parameters for read bias estimation
          default: ""

        calculatecontamination:
          type: string
          description: Optional parameters for strand contamination
          default: ""

        learnreadorientationmodel:
          type: string
          description: Optional parameters for read orientation models
          default: ""

        filtermutectcalls:
          type: string
          description: Optional parameters for VCF filtration
          default: "--create-output-variant-index --min-median-mapping-quality 35 --max-alt-allele-count 3"

        varianteval:
          type: string
          description: Optional parameters for variant evaluation
          default: ""

      snpeff:
        type: string
        description: Optional parameters for VCF genomic annotations
        default: ""

      snpsift:
        type: object
        description: Optional parameters for additional VCF annotations

        vartype:
          type: string
          description: Optional parameters for variant type annotation
          default: ""

      multiqc:
        type: string
        description: Optional parameters for MultiQC report aggregation
        default: "--verbose --no-megaqc-upload --no-ansi --force "
